"""Seed demo mining zones, equipment, and production history if tables are empty."""

from __future__ import annotations

import logging

from sqlalchemy.orm import Session

from app.database.connection import SessionLocal
from app.models.database_models import Equipment, MiningZone, ProductionHistory

logger = logging.getLogger(__name__)


def seed_if_empty() -> None:
    db: Session = SessionLocal()
    try:
        zones = [
            MiningZone(
                zone_name="Dongri Buzurg Sector 1",
                latitude=21.5312,
                longitude=79.6945,
                district="Bhandara",
                state="Maharashtra",
                mineral_type="Manganese",
                ore_grade=43.2,
                estimated_reserve=1.24,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Tirodi Deep Deposit",
                latitude=21.6789,
                longitude=79.7123,
                district="Balaghat",
                state="Madhya Pradesh",
                mineral_type="Manganese",
                ore_grade=41.5,
                estimated_reserve=0.88,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Ukwa East Horizon",
                latitude=21.9612,
                longitude=80.4631,
                district="Balaghat",
                state="Madhya Pradesh",
                mineral_type="Manganese",
                ore_grade=37.8,
                estimated_reserve=0.42,
                potential_level="MEDIUM",
            ),
            MiningZone(
                zone_name="Mamatwan Mine - Kalahari Basin",
                latitude=-27.4245,
                longitude=22.9814,
                district="Northern Cape",
                state="South Africa",
                mineral_type="Manganese",
                ore_grade=44.5,
                estimated_reserve=8.50,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Woodie Woodie Deposit - Pilbara",
                latitude=-21.6508,
                longitude=121.6425,
                district="East Pilbara",
                state="Australia",
                mineral_type="Manganese",
                ore_grade=46.8,
                estimated_reserve=3.20,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Moanda Plateau - Bangombe Basin",
                latitude=-1.5647,
                longitude=13.1978,
                district="Haut-Ogooué",
                state="Gabon",
                mineral_type="Manganese",
                ore_grade=49.2,
                estimated_reserve=5.10,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Mina do Azul - Carajás Mineral Complex",
                latitude=-5.9734,
                longitude=-50.4851,
                district="Pará",
                state="Brazil",
                mineral_type="Manganese",
                ore_grade=42.0,
                estimated_reserve=2.85,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Groote Eylandt - GEMCO Gulf Horizon",
                latitude=-13.9782,
                longitude=136.4475,
                district="Northern Territory",
                state="Australia",
                mineral_type="Manganese",
                ore_grade=45.3,
                estimated_reserve=4.60,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Chiatura Manganese Basin - Sachkhere Station",
                latitude=42.2903,
                longitude=43.2801,
                district="Imereti",
                state="Georgia",
                mineral_type="Manganese",
                ore_grade=42.5,
                estimated_reserve=3.10,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Nikopol Basin - Ordzhonikidze Pit Station",
                latitude=47.6580,
                longitude=34.3980,
                district="Dnipropetrovsk",
                state="Ukraine",
                mineral_type="Manganese",
                ore_grade=36.2,
                estimated_reserve=4.50,
                potential_level="MEDIUM",
            ),
            MiningZone(
                zone_name="Molango District - Otongo Underground Station",
                latitude=20.7872,
                longitude=-98.7289,
                district="Hidalgo",
                state="Mexico",
                mineral_type="Manganese",
                ore_grade=40.8,
                estimated_reserve=2.40,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Batesville Regional Mineral Station",
                latitude=35.7698,
                longitude=-91.6409,
                district="Arkansas",
                state="United States",
                mineral_type="Manganese",
                ore_grade=34.5,
                estimated_reserve=0.95,
                potential_level="MEDIUM",
            ),
            MiningZone(
                zone_name="Nsuta Deep Pit & Battery Ore Station",
                latitude=5.2917,
                longitude=-1.9792,
                district="Western Region",
                state="Ghana",
                mineral_type="Manganese",
                ore_grade=47.5,
                estimated_reserve=3.80,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Nchwaning Mine - Black Rock Deep Station",
                latitude=-27.1356,
                longitude=22.8423,
                district="Northern Cape",
                state="South Africa",
                mineral_type="Manganese",
                ore_grade=48.0,
                estimated_reserve=6.20,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Morro da Mina - Lafaiete Sinter Station",
                latitude=-20.6611,
                longitude=-43.7844,
                district="Minas Gerais",
                state="Brazil",
                mineral_type="Manganese",
                ore_grade=38.6,
                estimated_reserve=1.90,
                potential_level="MEDIUM",
            ),
            MiningZone(
                zone_name="Sandur Hills - Deogiri High-Grade Station",
                latitude=15.0847,
                longitude=76.5492,
                district="Ballari / Vijayanagara",
                state="Karnataka",
                mineral_type="Manganese",
                ore_grade=41.2,
                estimated_reserve=1.65,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Barbil - Keonjhar Valley Extraction Station",
                latitude=22.1227,
                longitude=85.3982,
                district="Keonjhar",
                state="Odisha",
                mineral_type="Manganese",
                ore_grade=44.0,
                estimated_reserve=2.10,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Bootu Creek - Tomkinson Basin Station",
                latitude=-18.8921,
                longitude=134.1956,
                district="Barkly",
                state="Australia",
                mineral_type="Manganese",
                ore_grade=43.8,
                estimated_reserve=1.85,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Serra do Navio Manganese & Ore Station",
                latitude=0.9012,
                longitude=-52.0028,
                district="Amapá",
                state="Brazil",
                mineral_type="Manganese",
                ore_grade=45.2,
                estimated_reserve=2.75,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Tshipi Borwa Open Pit Station",
                latitude=-27.3689,
                longitude=22.9642,
                district="Kalahari Basin",
                state="South Africa",
                mineral_type="Manganese",
                ore_grade=37.5,
                estimated_reserve=7.20,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Moa Bay Mineral & Ore Processing Station",
                latitude=20.6547,
                longitude=-74.9511,
                district="Holguín",
                state="Cuba",
                mineral_type="Manganese",
                ore_grade=39.8,
                estimated_reserve=1.45,
                potential_level="MEDIUM",
            ),
            MiningZone(
                zone_name="Postmasburg High-Purity Ore Station",
                latitude=-28.3331,
                longitude=23.0678,
                district="Northern Cape",
                state="South Africa",
                mineral_type="Manganese",
                ore_grade=43.1,
                estimated_reserve=3.15,
                potential_level="HIGH",
            ),
            MiningZone(
                zone_name="Hualien Silicate & Manganese Station",
                latitude=23.9769,
                longitude=121.6044,
                district="Hualien County",
                state="Taiwan",
                mineral_type="Manganese",
                ore_grade=35.4,
                estimated_reserve=0.82,
                potential_level="MEDIUM",
            ),
            MiningZone(
                zone_name="Kuruman Manganese Horizon Station",
                latitude=-27.4578,
                longitude=23.4325,
                district="Northern Cape",
                state="South Africa",
                mineral_type="Manganese",
                ore_grade=29.8,
                estimated_reserve=0.35,
                potential_level="LOW",
            ),
            MiningZone(
                zone_name="Sierra de Santa Ana Mineral Station",
                latitude=30.5412,
                longitude=-111.1245,
                district="Sonora",
                state="Mexico",
                mineral_type="Manganese",
                ore_grade=31.5,
                estimated_reserve=0.48,
                potential_level="LOW",
            ),
        ]

        existing_names = {row[0] for row in db.query(MiningZone.zone_name).all()}
        new_zones = [z for z in zones if z.zone_name not in existing_names]

        if new_zones:
            db.add_all(new_zones)
            db.flush()

            history = []
            for zone in new_zones:
                base = 62000.0 + (zone.id or 1) * 4000
                for year, bump in ((2021, 0), (2022, 3500), (2023, 7200), (2024, 9100), (2025, 11000)):
                    history.append(
                        ProductionHistory(
                            mining_zone_id=zone.id,
                            year=year,
                            production=base + bump,
                            ore_grade=zone.ore_grade,
                        )
                    )
            db.add_all(history)
            db.commit()

        db.add_all(
            [
                Equipment(
                    equipment_name="CAT 6020B Heavy Hydraulic Excavator",
                    equipment_type="Excavator",
                    mining_zone_id=zones[0].id,
                    status="OPERATIONAL",
                    operating_hours=4280,
                    efficiency=0.915,
                    last_maintenance="2026-01-12",
                ),
                Equipment(
                    equipment_name="Epiroc Pit Viper 271 Rotary Drill",
                    equipment_type="Drill Rig",
                    mining_zone_id=zones[1].id,
                    status="WARNING",
                    operating_hours=6120,
                    efficiency=0.742,
                    last_maintenance="2025-12-04",
                ),
                Equipment(
                    equipment_name="Metso Nordberg C160 Jaw Crusher",
                    equipment_type="Crusher",
                    mining_zone_id=zones[2].id,
                    status="MAINTENANCE",
                    operating_hours=5300,
                    efficiency=0.65,
                    last_maintenance="2026-08-30",
                ),
                Equipment(
                    equipment_name="Liebherr R 9800 Heavy Mining Excavator",
                    equipment_type="Excavator",
                    mining_zone_id=zones[3].id,
                    status="OPERATIONAL",
                    operating_hours=3820,
                    efficiency=0.934,
                    last_maintenance="2026-01-20",
                ),
                Equipment(
                    equipment_name="Komatsu PC4000-11 Super Hydraulic Shovel",
                    equipment_type="Excavator",
                    mining_zone_id=zones[4].id,
                    status="OPERATIONAL",
                    operating_hours=4120,
                    efficiency=0.902,
                    last_maintenance="2026-02-11",
                ),
                Equipment(
                    equipment_name="Hitachi EX5600-7 Heavy Mining Shovel",
                    equipment_type="Excavator",
                    mining_zone_id=zones[5].id,
                    status="OPERATIONAL",
                    operating_hours=2950,
                    efficiency=0.941,
                    last_maintenance="2026-02-05",
                ),
                Equipment(
                    equipment_name="Caterpillar 797F Ultra-Class Haul Fleet Unit",
                    equipment_type="Haul Truck",
                    mining_zone_id=zones[6].id,
                    status="WARNING",
                    operating_hours=6480,
                    efficiency=0.785,
                    last_maintenance="2025-11-28",
                ),
                Equipment(
                    equipment_name="Sandvik DR416i Rotary Blasthole Drill",
                    equipment_type="Drill Rig",
                    mining_zone_id=zones[7].id,
                    status="OPERATIONAL",
                    operating_hours=3210,
                    efficiency=0.920,
                    last_maintenance="2026-01-15",
                ),
                Equipment(
                    equipment_name="FAM Gantry Bucket-Wheel Reclaimer",
                    equipment_type="Reclaimer",
                    mining_zone_id=zones[8].id,
                    status="OPERATIONAL",
                    operating_hours=3410,
                    efficiency=0.912,
                    last_maintenance="2026-01-22",
                ),
                Equipment(
                    equipment_name="Bucyrus-Erie 1570W Walking Dragline",
                    equipment_type="Dragline",
                    mining_zone_id=zones[9].id,
                    status="WARNING",
                    operating_hours=7250,
                    efficiency=0.765,
                    last_maintenance="2025-10-15",
                ),
                Equipment(
                    equipment_name="Sandvik TH551i Heavy Underground Hauler",
                    equipment_type="Haul Truck",
                    mining_zone_id=zones[10].id,
                    status="OPERATIONAL",
                    operating_hours=4180,
                    efficiency=0.898,
                    last_maintenance="2026-02-02",
                ),
                Equipment(
                    equipment_name="Caterpillar 988K Heavy Wheel Loader",
                    equipment_type="Loader",
                    mining_zone_id=zones[11].id,
                    status="OPERATIONAL",
                    operating_hours=3890,
                    efficiency=0.884,
                    last_maintenance="2026-01-18",
                ),
                Equipment(
                    equipment_name="Hitachi ZX890LCH-5A Mining Excavator",
                    equipment_type="Excavator",
                    mining_zone_id=zones[12].id,
                    status="OPERATIONAL",
                    operating_hours=3310,
                    efficiency=0.932,
                    last_maintenance="2026-02-14",
                ),
                Equipment(
                    equipment_name="Normet Spraymec 8100 VC Concrete Sprayer",
                    equipment_type="Support Rig",
                    mining_zone_id=zones[13].id,
                    status="OPERATIONAL",
                    operating_hours=2740,
                    efficiency=0.945,
                    last_maintenance="2026-02-19",
                ),
                Equipment(
                    equipment_name="Komatsu HD785-7 Off-Highway Haul Fleet",
                    equipment_type="Haul Truck",
                    mining_zone_id=zones[14].id,
                    status="MAINTENANCE",
                    operating_hours=5910,
                    efficiency=0.690,
                    last_maintenance="2026-02-28",
                ),
                Equipment(
                    equipment_name="Volvo EC750D Crawler Excavator",
                    equipment_type="Excavator",
                    mining_zone_id=zones[15].id,
                    status="OPERATIONAL",
                    operating_hours=3670,
                    efficiency=0.908,
                    last_maintenance="2026-01-30",
                ),
                Equipment(
                    equipment_name="Tata Hitachi ZAXIS 470H Mining Excavator",
                    equipment_type="Excavator",
                    mining_zone_id=zones[16].id,
                    status="OPERATIONAL",
                    operating_hours=3950,
                    efficiency=0.925,
                    last_maintenance="2026-02-08",
                ),
                Equipment(
                    equipment_name="Caterpillar 777G Off-Highway Truck",
                    equipment_type="Haul Truck",
                    mining_zone_id=zones[17].id,
                    status="OPERATIONAL",
                    operating_hours=4320,
                    efficiency=0.887,
                    last_maintenance="2026-01-25",
                ),
            ]
        )
        db.commit()
        logger.info("Seeded demo mining zones, production history, and equipment")
    except Exception:
        db.rollback()
        logger.exception("Failed to seed demo data")
    finally:
        db.close()
